# Generated by Django 3.1.7 on 2021-03-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formular',
            options={'verbose_name_plural': 'formular'},
        ),
    ]
