# Generated by Django 3.1.7 on 2021-03-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_app', '0002_auto_20210324_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formular',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
